package com.google.service.models

// This code was autogenerated

import spray.json.DefaultJsonProtocol

case class Activities(offset: Option[Int] = None, limit: Option[Int] = None, count: Option[Int] = None, history: Option[Seq[Activity]] = None)

object Activities {
  implicit val format = jsonFormat4(Activities)
}

case class Activity(uuid: Option[String] = None)

object Activity {
  implicit val format = jsonFormat1(Activity)
}

case class Error(code: Option[Int] = None, message: Option[String] = None, fields: Option[String] = None)

object Error {
  implicit val format = jsonFormat3(Error)
}

case class PriceEstimate(productId: Option[String] = None, currencyCode: Option[String] = None, displayName: Option[String] = None, estimate: Option[String] = None, lowEstimate: Option[Double] = None, highEstimate: Option[Double] = None, surgeMultiplier: Option[Double] = None)

object PriceEstimate {
  implicit val format = jsonFormat7(PriceEstimate)
}

case class Product(productId: Option[String] = None, description: Option[String] = None, displayName: Option[String] = None, capacity: Option[String] = None, image: Option[String] = None)

object Product {
  implicit val format = jsonFormat5(Product)
}

case class Profile(firstName: Option[String] = None, lastName: Option[String] = None, email: Option[String] = None, picture: Option[String] = None, promoCode: Option[String] = None)

object Profile {
  implicit val format = jsonFormat5(Profile)
}
