package com.google.service.models

// This code was autogenerated

import spray.json.DefaultJsonProtocol

case class Activities(offset: Int, limit: Int, count: Int, history: Seq[Activity])

object Activities {
  implicit val format = jsonFormat4(Activities)
}

case class Activity(uuid: String)

object Activity {
  implicit val format = jsonFormat1(Activity)
}

case class Error(code: Int, message: String, fields: String)

object Error {
  implicit val format = jsonFormat3(Error)
}

case class PriceEstimate(productId: String, currencyCode: String, displayName: String, estimate: String, lowEstimate: Double, highEstimate: Double, surgeMultiplier: Double)

object PriceEstimate {
  implicit val format = jsonFormat7(PriceEstimate)
}

case class Product(productId: String, description: String, displayName: String, capacity: String, image: String)

object Product {
  implicit val format = jsonFormat5(Product)
}

case class Profile(firstName: String, lastName: String, email: String, picture: String, promoCode: String)

object Profile {
  implicit val format = jsonFormat5(Profile)
}
